baseURL = "https://dbs.ifi.lmu.de"
languageCode = "en"
title = "Data Mining Lab @LMU"
paginate = 3

[module]
[[module.mounts]]
  source = 'static'
  target = 'static'
	excludeFiles = ['images/**/archive']

disableKinds = ['taxonomy', 'term']

[outputFormats.Publications]
mediaType = "application/json"
baseName = "publications"
isPlainText = true
notAlternative = true

[outputFormats.Software]
mediaType = "application/json"
baseName = "software"
isPlainText = true
notAlternative = true

[outputFormats.News]
mediaType = "application/json"
baseName = "news"
isPlainText = true
notAlternative = true
	
[outputs]
   home = [ "HTML", "Publications", "Software", "News" ]
   
[frontmatter]
	lastmod = ["lastmod", ":fileModTime"]

#[taxonomies]
#  category = 'categories'
#  series = 'series'
#  tag = 'tags'

[blackfriday]
extensions = ["hardLineBreak"]
[markup.goldmark.renderer]
unsafe="true"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5
    
[params]

# ----------------------------------------------------------------------------------------
# Navigation
# ----------------------------------------------------------------------------------------      
[params.navigation]
	home  = "Home"
    logo = "images/dmlab.png"
	  
	# Team  
  [[params.navigation.entry]]
    id = "team"
    name = "Team"
    linkto = "/team/"
    hasChildren = "true"
    
  [[params.navigation.subentry]]
    parent = "team"
    linkto = "/team/professors/"
    name = "Professors"
    
  [[params.navigation.subentry]]
    parent = "team"
    linkto = "/team/office/"
    name = "Office" 
    #divider = true
    
  [[params.navigation.subentry]]
    parent = "team"
    linkto = "/team/scientists/"
    name = "Scientists"
    
  [[params.navigation.subentry]]
    parent = "team"
    linkto = "/team/alumni/"
    name = "Alumni"
    
  # Studies #  
  [[params.navigation.entry]]
    id = "studies"
    name = "Studies"
    linkto = "/studies/"
    hasChildren = "false"
    
  # Research #  
  [[params.navigation.entry]]
    id = "research"
    name = "Research"
    linkto = "/research/"
    hasChildren = "false"
    
  #	[[params.navigation.subentry]]
    #	  parent = "research"
    #	linkto = "/research/areaa/"
    #	  name = "A | Foundations of ML"
    
  [[params.navigation.entry]]
    id = "news"
    name = "News"
    linkto = "/news/"
    
  # Jobs #    
  [[params.navigation.entry]]
    id = "jobs"
    name = "Jobs"
    linkto = "/opportunities/"	
    hasChildren = "false"  
	  
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/funding/"
#	  name = "Funding Programs"
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/education/"
#	  name = "Education Programs"
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/training/"
#	  name = "Professional Training"
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/jobs/"
#	  name = "Jobs"

  [[params.navigation.entry]]
    id = "contact"
    name = "Contact"
    linkto = "/contact/"
	  
# ----------------------------------------------------------------------------------------
# Disable all tracking (DSVGO)
# ----------------------------------------------------------------------------------------
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
