baseURL = "https://dbs.ifi.lmu.de"
languageCode = "en"
title = "German AI Centers of Excellence"

[module]
[[module.mounts]]
  source = 'static'
  target = 'static'
	excludeFiles = ['images/**/archive']

disableKinds = ['taxonomy', 'term']

  
[frontmatter]
	lastmod = ["lastmod", ":fileModTime"]

#[taxonomies]
#  category = 'categories'
#  series = 'series'
#  tag = 'tags'

[blackfriday]
extensions = ["hardLineBreak"]
[markup.goldmark.renderer]
unsafe="true"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5
    
[params]

[[params.aicenter]]
name = "DFKI"
image = "/images/logos/dfki.jpg"
link = "https://www.dfki.de/web"

[[params.aicenter]]
name = "BIFOLD"
image = "/images/logos/bifold.jpg"
link = "https://www.bifold.berlin"

[[params.aicenter]]
name = "Scads.AI"
image = "/images/logos/scads.webp"
link = "https://scads.ai"

[[params.aicenter]]
name = "LAMARR"
image = "/images/logos/lamarr.webp"
link = "https://lamarr-institute.org"

[[params.aicenter]]
name = "Tue.AI"
image = "/images/logos/tueai.jpg"
link = "https://tuebingen.ai"

[[params.aicenter]]
name = "MCML"
image = "/images/logos/mcml.webp"
link = "https://mcml.ai"

# ----------------------------------------------------------------------------------------
# Navigation
# ----------------------------------------------------------------------------------------      
[params.navigation]
	home  = "Home"
    logo = "images/aicenters.png"
	  
  # About  
  [[params.navigation.entry]]
    id = "about"
    name = "About"
    linkto = "/about/"
    hasChildren = "false"
    
  # Studies #  
  [[params.navigation.entry]]
    id = "studies"
    name = "Studies"
    linkto = "/studies/"
    hasChildren = "false"
    
  # Research #  
  [[params.navigation.entry]]
    id = "research"
    name = "Research"
    linkto = "/research/"
    hasChildren = "false"
    
  #	[[params.navigation.subentry]]
    #	  parent = "research"
    #	linkto = "/research/areaa/"
    #	  name = "A | Foundations of ML"
    
  [[params.navigation.entry]]
    id = "news"
    name = "News"
    linkto = "/news/"
    
  # Jobs #    
  [[params.navigation.entry]]
    id = "jobs"
    name = "Jobs"
    linkto = "/opportunities/"	
    hasChildren = "false"  
	  
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/funding/"
#	  name = "Funding Programs"
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/education/"
#	  name = "Education Programs"
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/training/"
#	  name = "Professional Training"
#	[[params.navigation.subentry]]
#	  parent = "opportunities"
#	  linkto = "/opportunities/jobs/"
#	  name = "Jobs"

  [[params.navigation.entry]]
    id = "contact"
    name = "Contact"
    linkto = "/contact/"
	  
# ----------------------------------------------------------------------------------------
# Disable all tracking (DSVGO)
# ----------------------------------------------------------------------------------------
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
